### ISSUE TITLE
Bot does not recognize command of form `/command@usernamebot`

### ISSUE THREAD

**Issue by iamcosmin** [HeySreelal/televerse#102]
Currently, creating a command handler (`bot.command`) recognizes commands like `/start`, but not `/start@usernamebot`. In supergroups, when there are multiple bots, if you click on a command provided by the bot, the Telegram client will automatically send a message with the command, followed by the bot username (like shown above).

**Comment by HeySreelal** [comment]
Hey, thanks for raising this. Yeah, this is indeed a bug. Surely fix that shortly. 

Thanks again :)

**Comment by iamcosmin** [comment]
Thank you so much.
Also, a nitpick in Readme, in the Thank you section
`Televerse is a powerful and easy-to-use library for building Telegram bots in TypeScript.`
Should be Dart instead of TypeScript

**Comment by HeySreelal** [comment]
> Thank you so much. Also, a nitpick in Readme, in the Thank you section `Televerse is a powerful and easy-to-use library for building Telegram bots in TypeScript.` Should be Dart instead of TypeScript

Yeah yeah, I'm aware of that. Already fixed that on c9dd6fc3d7122fb4d5883efb976c3549d64efaa9. Of course, some GPT things 😬

Once again, thank you so much for reporting and this is all good on v1.9.9 :)
