### ISSUE TITLE
Commands sent in groups with topics make the bot reply in the wrong topic

### ISSUE THREAD

**Issue by iamcosmin** [HeySreelal/televerse#110]
If you send a command in a chat topic, the bot will always reply in the principal topic, but it should reply in the same topic in which the command has been sent. The only way to circumvent this behaviour is to always specify the `messageThreadId`, but I do think it would be a great idea if it was specified by default.

**Comment by HeySreelal** [comment]
Just a quick update, this has been added in v1.9.12 ✨
