### ISSUE TITLE
Minor updates 🚧

### ISSUE THREAD

**Issue by HeySreelal** [HeySreelal/televerse#113]
Here are some pending changes to be made:

- [x] Update the main example file
- [x] Update README

**Comment by abhishek09827** [comment]
Hello pls assign this task to me

**Comment by HeySreelal** [comment]
Please go ahead and take it up, I'll stand by to see your PR in the near future :)

**Comment by HeySreelal** [comment]
Hey, please lemme know if you're on this :)
