### ISSUE TITLE
Suggestion: Add `InputFile.fromBytes`

### ISSUE THREAD

**Issue by iamcosmin** [HeySreelal/televerse#138]
Currently, files can be uploaded by `File`, fileId or url.
I think uploading a file by bytes (`Uint8List`) should also be included as a shortcut, because getting a file via http returns bodyBytes, and in the current implementation I have to set up a temporary folder, then save that file on the disk, only for it to be processed right after saving and then deleted. It seems counterintuitive in this scenario.

**Comment by HeySreelal** [comment]
Perfect, that'll be great as well. Will add it to the next release. Thanks for shooting this.

**Comment by HeySreelal** [comment]
So basically, the temporary file creation code should be in the library to make it easier right? 

I'm not sure there's another way for this actually.
