### ISSUE TITLE
How to check if the bot instance is already running or not?

### ISSUE THREAD

**Issue by OttomanDeveloper** [HeySreelal/televerse#147]
How to check if the bot instance is already running or not?
I'm getting this error.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LongPollingException [null]: Already polling. You cannot start another polling when another polling is working.

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: TelegramException [429]: (Too Many Requests: retry after 94)

**Comment by HeySreelal** [comment]
Are you calling the `Televerse.start` method more than once? It might possibly cause this exception to be thrown.

Hmm, seems an interesting topic. As of now, there's no way you can check if a bot is already started the polling or not.

**Comment by HeySreelal** [comment]
Maybe we can add a `bot.isPolling` flag for that.

**Comment by HeySreelal** [comment]
Btw, if you're using LongPolling as a fetcher, you can already check if the long polling is active:

```dart
    if((bot.fetcher as LongPolling).isPolling) {
      print('Polling is active');
    } else {
      print('Polling is not active');
    }
```

**Comment by OttomanDeveloper** [comment]
Thank you it's working

**Comment by HeySreelal** [comment]
Happy to help! Happy Televersing! 🚀
