### ISSUE TITLE
There is no way to end the "Conversation"

### ISSUE THREAD

**Issue by neyrodzen** [HeySreelal/televerse#208]
The conversation continues to be monitored until the desired message arrives.  Sometimes you need to cancel a Conversation because the user switches to another handler, but the Conversation is interfering with it.

**Comment by HeySreelal** [comment]
Thank you so much for raising this. I've added a tweak to the code and now all methods in the `Conversation` class accepts a boolean parameter `clearUnfulfilled` which when true clears all the unfulfilled listeners. Hence fixing this issue. By default the `clearUnfulfilled` parameter will be `true`.

Code has been updated on the `dev` branch, feel free to test it and let me know if this helps.

**Comment by neyrodzen** [comment]
Thank you, you don’t even have to change anything in the code 👍

**Comment by HeySreelal** [comment]
Glad it is solved! Will push it to release in a few hours.

Happy Televersing! 🚀

**Comment by neyrodzen** [comment]
I don't want to bother you, but it would be great to add an explicit method to close the conversation, because when the user calls another handler during the Conversation, you need to kill this process

**Comment by HeySreelal** [comment]
For a better understanding, are you asking about a method to clear all the listeners?

**Comment by neyrodzen** [comment]
I think yes, it's best to have a static method to end all Conversations

**Comment by HeySreelal** [comment]
Hey again, thanks for raising the concern. I've added two methods to stop and clean listening to particular updates with Conversation. 

1. `Conversation.clear` - this method accepts the `ID` parameter to stop and clean active listeners for the mentioned chat.
2. `Conversation.clearAll` - this method clears all the active listeners of the particular conversation instance.

Both are not static methods, as we have to track the names of the handler scopes to cherry pick and cancel them.

Hope this helps.

**Comment by neyrodzen** [comment]
Super, everything works. You can split Conversations by name and stop the desired instance. Thanks  🫶

**Comment by HeySreelal** [comment]
Perfect! Will soon merge this into release.
