### ISSUE TITLE
IDs in some methods should be optional

### ISSUE THREAD

**Issue by Sominemo** [HeySreelal/televerse#212]
I noticed that methods related to MenuButton have an optional ID field in Telegram API, but televerse uses a non-nullable ID type. Telegram only accepts either a valid ID or absence of the field, so a hack like `ID.create("")` doesn't work. Absence of the field is used to set default state for the property.

There might be other fields like this one with a similar omission.

![image](https://github.com/HeySreelal/televerse/assets/19842935/577236d8-2a8c-4630-944f-03a433f6a2f0)

**Comment by Sominemo** [comment]
As a side question while I'm on it, is it possible to send a custom request? I didn't find a method like it and RawApi seems to be non-extensible. but it would help in blocker cases like this one.

**Comment by HeySreelal** [comment]
Hey, thanks for reporting! This must be a mistake from my side. As per the documentation the `setChatMenuButton` method only requires the `MenuButton` and not the `chat_id`. 

I'll fix this within a couple of hours.

And for the second question, as of now, we don't have a method to make custom request. But it sounds like a good idea as well! Will look into this in the next releases!

**Comment by HeySreelal** [comment]
Hey @Sominemo, just released v1.13.3 to pub.dev. Thanks again for raising the issue. Please feel free to raise more, or discuss in our [Telegram chat](https://telegram.me/televersedart), I guess you're already in there! ✨
