### ISSUE TITLE
Unhandled exception: type 'bool' is not a subtype of type 'Map<String, dynamic>' #0      RawAPI.sendChatAction (package:televerse/src/televerse/raw_api.dart:1174:26) <asynchronous suspension> #1      MessageMixin.replyWithChatAction (package:televerse/src/televerse/context/mixins/message_mixin.dart:459:12) <asynchronous suspension>

### ISSUE THREAD

**Issue by deargosep** [HeySreelal/televerse#52]
```
Unhandled exception:
type 'bool' is not a subtype of type 'Map<String, dynamic>'
#0      RawAPI.sendChatAction (package:televerse/src/televerse/raw_api.dart:1174:26)
<asynchronous suspension>
#1      MessageMixin.replyWithChatAction (package:televerse/src/televerse/context/mixins/message_mixin.dart:459:12)
<asynchronous suspension>
```

**Comment by HeySreelal** [comment]
Hey, thanks for reporting. I'll check this and fix this as soon as possible :)

**Comment by HeySreelal** [comment]
Hello there! I wanted to give you an update on the issue you reported. I've managed to resolve it on `Televerse v.1.5.1`. (Check out #53 for details). Thank you very much for bringing it to our attention and assisting us in enhancing the package.

I'd also like to mention that you're more than welcome to join the conversation at [@TeleverseDart](https://t.me/televersedart).

Best regards :)
