### ISSUE TITLE
Long polling doesn't handle flood errors

### ISSUE THREAD

**Issue by GiuseppeFn** [HeySreelal/televerse#83]
As the title suggests, the long polling class doesn't handle flood errors like it should (Delaying the next getUpdate request) and creates this: 
```
Unhandled exception:
Long polling stopped: Too Many Requests: retry after 5
#0      LongPolling._poll (package:televerse/src/televerse/fetch/long_polling.dart:92:9)
<asynchronous suspension>
#1      LongPolling.start (package:televerse/src/televerse/fetch/long_polling.dart:62:7)
<asynchronous suspension>
```

**Comment by HeySreelal** [comment]
Hey, thanks for reporting this. Have you passed an error handler method using the `Televerse.onError` method? Or is this issue happens even when the error handler is passed?

Let me know please :)

**Comment by HeySreelal** [comment]
Okay, I get it. So, what about stopping the polling when a LongPolling exception happens, then awaits the user's onError handler, and then restarting the polling?

Do you think that will work?

**Comment by GiuseppeFn** [comment]
This would probably do the trick, but i'd probably just handle it myself, as there are not many ways someone who uses the library would handle this (Meaning they would probably just handle it by sleeping the required time)

**Comment by HeySreelal** [comment]
Thanks again, this behavior is added in this commit: 9c56dffa3038c82e3b1a00d6346b6d6e06ce1901. 

Also, this is a minor breaking change as `HttpException` is now completely replaced with `TelegramException`. Telegram Exception contains the ResponseParameter object by which users can decide if they need to retry the request or not. 

The auto-retry behavior is added to the LongPolling at its core now. When a retriable long polling exception is thrown, the polling will be stopped for the specified time and auto-restarts after it.

Thanks again for reporting this.

**Comment by GiuseppeFn** [comment]
I'm very happy to had given you a little hand :)
