### ISSUE TITLE
Wrong condition while checking for command name

### ISSUE THREAD

**Issue by GiuseppeFn** [HeySreelal/televerse#85]
In a situation like this:
```
bot.command('test', test);
bot.command('testing', testing);
```
Both "test" and "testing" will be matched if the command is /test, this is probably because the command checks using a "startswith"

I suggest to split the command text by spaces, then check if the first element equals "/$command"

**Comment by HeySreelal** [comment]
Thanks a lot for bringing this to my attention. I appreciate your input, as I clearly haven't considered this particular scenario earlier.

The code has been rectified in commit 4057c9b78e189c3ae60b0d6f604791af4f595fd0. The upcoming update will include this fix.

Once again, thank you for your contribution.
